repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: double-quote-string-fixer
    -   id: check-shebang-scripts-are-executable
    -   id: pretty-format-json
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: mixed-line-ending
    -   id: sort-simple-yaml
-   repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
